-- 거시 경제 지표 (FRED, ECOS 등)
CREATE TABLE IF NOT EXISTS macro_indicators (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date DATE NOT NULL,
    indicator_name VARCHAR(50), -- 'CPI', 'FED_RATE', 'KR_RATE'
    value FLOAT,
    period_type VARCHAR(20), -- 'MONTHLY', 'QUARTERLY'
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(date, indicator_name)
);

-- 시장 데이터 (주식, 코인)
CREATE TABLE IF NOT EXISTS market_daily (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date DATE NOT NULL,
    ticker VARCHAR(20), -- 'AAPL', 'KRW-BTC', '005930'
    close_price FLOAT,
    volume FLOAT,
    market_cap FLOAT,
    asset_type VARCHAR(10), -- 'STOCK_US', 'STOCK_KR', 'CRYPTO'
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(date, ticker)
);

-- 기업 실적 (분기별)
CREATE TABLE IF NOT EXISTS corporate_quarterly (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticker VARCHAR(20),
    year INT,
    quarter INT, -- 1, 2, 3, 4
    revenue FLOAT, -- 매출
    operating_income FLOAT, -- 영업이익
    net_income FLOAT, -- 당기순이익
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(ticker, year, quarter)
);
